# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [5]:
import numpy as np

In [6]:
#1 - Crear un arreglo de ceros de longitud 12
arreglo_Ceros = np.zeros(12)
print(arreglo_Ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#2 - Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

In [13]:
arreglo_Ceros = np.zeros(10)
arreglo_Ceros[5] = 10
print(arreglo_Ceros)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [14]:
#3 - Crear un arreglo que tenga los números del 10 al 49

In [15]:
arreglo_Numeros = np.arange(10, 50)
print(arreglo_Numeros)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
#4 - Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [17]:
# Crea un arreglo unidimensional con los números del 0 al 8
arreglo_Unidimensional = np.arange(9)

# Modifico el arreglo unidimensional en un arreglo 2D de forma (3, 3)
arreglo_2d = arreglo_Unidimensional.reshape(3, 3)
print(arreglo_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
#5 - Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [20]:
arreglo_Aleatorio = np.random.rand(100)

print(arreglo_Aleatorio)

[0.5511186  0.07725417 0.09487092 0.95571763 0.89404641 0.88573278
 0.99235013 0.93882913 0.14859643 0.67456876 0.36874872 0.24916833
 0.58703961 0.84958248 0.52854367 0.41373512 0.25709364 0.65257619
 0.40002273 0.55434156 0.90682717 0.96159824 0.65598609 0.9200566
 0.31652953 0.70695986 0.46617799 0.81804623 0.97365224 0.45271411
 0.68055586 0.82795012 0.68540959 0.03263218 0.41496008 0.4756601
 0.36000088 0.40476036 0.08612514 0.3184533  0.97599464 0.6429437
 0.16911686 0.70616795 0.07388734 0.76205561 0.17768784 0.29294554
 0.49836042 0.95652129 0.91079305 0.51717834 0.31435312 0.48571207
 0.33886365 0.5175648  0.02880413 0.92040497 0.90327248 0.43935711
 0.12282129 0.81464897 0.66462642 0.0267125  0.18075608 0.82949768
 0.10572625 0.22044783 0.92315898 0.63985049 0.03663071 0.95170702
 0.98969965 0.27767971 0.16410587 0.89501123 0.28055287 0.7335413
 0.31654744 0.38029373 0.03765196 0.18810397 0.81138514 0.90063529
 0.52234694 0.95578596 0.54980709 0.28649025 0.20415246 0.05157777

In [22]:
# Calcula la media del arreglo
media = np.mean(arreglo_aleatorio)
print(media)

# Calcula la varianza del arreglo
varianza = np.var(arreglo_aleatorio)
print(varianza)

0.5286188547299807
0.09496632472608044


In [23]:
#6 - Calcular la media de un arreglo usando np.sum

In [24]:
arreglo = np.array([1, 2, 3, 4, 5])

media = np.sum(arreglo) / len(arreglo)
print("Media:", media)

Media: 3.0


In [29]:
#7 - Calcular la varianza de un arreglo usando np.sum y np.mean

In [31]:
arreglo = np.array([1, 2, 3, 4, 5])

media = np.mean(arreglo)
varianza = np.sum((arreglo - media)**2) / len(arreglo)

print("Varianza:", varianza)

Varianza: 2.0


In [32]:
#8 - Crear un array de números aleatorios usando np.random.randn.

In [33]:
arreglo_Aleatorio = np.random.randn(10)

print(arreglo_Aleatorio)

[ 0.66202422 -1.11190271 -0.36326655 -1.43215395 -0.10447187 -0.61623257
 -0.00632064  1.03686515  0.80930549 -0.10315416]
